# Generated by Django 6.0.5 on 2026-06-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apikey_intelligencesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencesubmission',
            name='pipeline_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='intelligencesubmission',
            name='current_stage',
            field=models.IntegerField(choices=[(0, 'Problem Framing & IPO'), (1, 'Pendefinisian Model Dataset'), (2, 'Pemrosesan Data'), (3, 'Perencanaan Model & Refining'), (4, 'Pelatihan & Testing Model'), (5, 'Refining Model'), (6, 'Materi Komunikasi Teknikal'), (7, 'Materi Komunikasi Manajemen')], default=0),
        ),
    ]
