# Generated by Django 6.0.4 on 2026-06-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_intelligencesubmission_pipeline_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIUXIssue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_key', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('story_points', models.CharField(blank=True, max_length=50, null=True)),
                ('labels', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('meaningful_objectives', models.JSONField(blank=True, null=True)),
                ('intelligence_experience', models.JSONField(blank=True, null=True)),
                ('intelligence_implementation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_issues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UIUXProject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UIUXSprint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'core_sprints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UIUXUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'core_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IssueCreationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uiux_issue_id', models.IntegerField(unique=True)),
                ('realization_status', models.IntegerField(default=0)),
                ('development_constraints', models.TextField(blank=True, null=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrchestrationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uiux_issue_id', models.IntegerField()),
                ('category', models.CharField(choices=[('Planning', 'Planning'), ('Development', 'Development'), ('Testing', 'Testing'), ('Maintenance', 'Maintenance')], max_length=50)),
                ('status', models.CharField(default='in_progress', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
