# Generated by Django 6.0.5 on 2026-06-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_uiuxissue_uiuxproject_uiuxsprint_uiuxuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIUXAttachment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=500)),
                ('mimetype', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_attachments',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='intelligencesubmission',
            name='detected_data_type',
            field=models.CharField(choices=[('image', 'Gambar'), ('tabular', 'Tabular (CSV/Excel)'), ('text', 'Teks'), ('numeric', 'Numerik'), ('mixed', 'Campuran'), ('unknown', 'Belum Terdeteksi'), ('csv', 'CSV'), ('txt', 'TXT'), ('json', 'JSON')], default='unknown', max_length=20),
        ),
    ]
